image: registry.gitlab.com/jjalling/rpibuilder:latest

stages:
  - source
  - build

cache:
  paths:
    - build/

source:
  when: manual
  stage: source
  script:
    - ls

build:release_nocmake:
  when: manual
  stage: build
  script:
    - pwd
    - ls -l CMakeFiles
    - ls -l zip/CMakeFiles/minizip.dir/unzip.c.o
    - make

build:release:
  when: manual
  stage: build
  script:
    - pwd
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j 4
