image: registry.gitlab.com/jjalling/rpibuilder:latest

stages:
  - source
  - build

source:
  when: manual
  stage: source
  script:
    - ls

build:release:
  when: manual
  stage: build
  cache:
    paths:
      - "*.o"
  script:
    - pwd
    - cmake -DCMAKE_BUILD_TYPE=Release .
    - make
